"""Translate the intent-based install block into the mechanism operations the executor runs.

ADR-0026 frames the manifest as four named sections that declare WHAT lands where, never a
path or a mechanism: `place` (a payload file of a destination class), `instrument` (a carried
diff against a pre-existing file), `service` (a managed long-running process), and `restart`
(core-service hooks). The adapter owns the class-to-(path, mechanism) mapping.

Until the daemon dispatches each verb to a per-printer adapter (ADR-0029), this module is the
thin U1 seam: it maps each new section to the legacy `{symlinks, templates, patches, start,
dirs}` operations the current executor already knows how to run, merging in any legacy keys a
not-yet-migrated manifest still carries. The path templates and restart commands here are the
U1 defaults; moving them behind the adapter contract is the follow-on.
"""
from pathlib import PurePosixPath

# A destination class resolves to a path template using adapter variables the daemon expands
# at install time. Grows empirically as plugins of new classes are repacked.
PLACEMENT_DESTINATIONS = {
    "klipper-config": "$BESPOK3D_KLIPPER/{name}",
    "moonraker-config": "$BESPOK3D_MOONRAKER/{name}",
    "klipper-extra": "$KLIPPER_EXTRAS/{name}",
    "moonraker-component": "$MOONRAKER_COMPONENTS/{name}",
    "web-location": "$BESPOK3D/etc/nginx/locations/{name}",
    "system-bin": "$BESPOK3D/bin/{name}",
}

# A managed service (ADR-0026/0029) is realized by the adapter generating an init script the
# daemon writes under this dir inside the plugin and wires into the autostart dir. The script
# CONTENT is the adapter's HOW (start_script.py); the wiring here is the core vocabulary.
SERVICE_SCRIPT_DIR = "etc/init.d"
SERVICE_AUTOSTART_DEST = "$BESPOK3D/etc/init.d/autostart/{script}"

# An instrumentation target (ADR-0031) resolves to the pre-existing file the carried diff patches.
# The name is logical (relative to the Klipper tree), never a raw path.
INSTRUMENT_DESTINATIONS = {
    "klipper-source": "$KLIPPER_SRC/{name}",
}

# A core-service hook resolves to the printer's restart command (U1 default until the adapter
# service hooks of ADR-0029 own this).
RESTART_HOOKS = {
    "klipper": "/etc/init.d/S60klipper restart",
    "moonraker": "/etc/init.d/S61moonraker restart",
    "web": "/usr/sbin/nginx -s reload",
    "lmd": "$BESPOK3D/etc/init.d/lmdctl restart",
}

DATA_DIR_TEMPLATE = "$BESPOK3D/var/lib/{name}"


def _placement_target(placement: dict) -> tuple[str, str]:
    destination_class = placement["class"]
    target_name = placement.get("name") or PurePosixPath(placement["src"]).name
    template = PLACEMENT_DESTINATIONS.get(destination_class)
    if template is None:
        raise ValueError(f"unsupported destination class: {destination_class}")
    return template.format(name=target_name), target_name


def _placement_ops(placement: dict) -> tuple[dict | None, dict]:
    """Return (template_op_or_None, symlink_op) realizing one placement.

    A `render` placement first writes the variable-substituted file beside the template inside
    the plugin dir, then symlinks that rendered file into the destination.
    """
    source = placement["src"]
    destination, target_name = _placement_target(placement)
    if not placement.get("render"):
        return None, {"from": source, "to": destination}
    rendered = str(PurePosixPath(source).parent / target_name)
    return {"from": source, "to": rendered}, {"from": rendered, "to": destination}


def _instrument_op(entry: dict) -> dict:
    instrument_class = entry["class"]
    template = INSTRUMENT_DESTINATIONS.get(instrument_class)
    if template is None:
        raise ValueError(f"unsupported instrument class: {instrument_class}")
    return {"file": template.format(name=entry["name"]), "patch": entry["diff"]}


def service_script_name(service: dict) -> str:
    return f"s65{service['name']}"


def _service_ops(service: dict) -> tuple[dict, str | None, str]:
    """Return (autostart_symlink, start_command_or_None, stop_command) for one managed service.

    The script itself is generated by the adapter before the symlink is realized; here we only
    wire the generated script into the autostart dir and produce the start/stop hooks.
    """
    script = service_script_name(service)
    source = f"{SERVICE_SCRIPT_DIR}/{script}"
    destination = SERVICE_AUTOSTART_DEST.format(script=script)
    symlink = {"from": source, "to": destination}
    start = f"{destination} restart" if service.get("autostart") else None
    return symlink, start, f"{destination} stop"


def _placement_additions(placements: list[dict]) -> tuple[list[dict], list[dict]]:
    templates: list[dict] = []
    symlinks: list[dict] = []
    for placement in placements:
        template_op, symlink_op = _placement_ops(placement)
        if template_op is not None:
            templates.append(template_op)
        symlinks.append(symlink_op)
    return templates, symlinks


def _service_additions(services: list[dict]) -> tuple[list[dict], list[str], list[str]]:
    symlinks: list[dict] = []
    starts: list[str] = []
    stops: list[str] = []
    for service in services:
        symlink_op, start_cmd, stop_cmd = _service_ops(service)
        symlinks.append(symlink_op)
        if start_cmd is not None:
            starts.append(start_cmd)
        stops.append(stop_cmd)
    return symlinks, starts, stops


def _restart_commands(hooks: list[str]) -> list[str]:
    commands = []
    for hook in hooks:
        command = RESTART_HOOKS.get(hook)
        if command is None:
            raise ValueError(f"unsupported restart hook: {hook}")
        commands.append(command)
    return commands


def normalize_install(install: dict) -> dict:
    """Merge any legacy install keys with the translated intent sections into legacy ops."""
    place_templates, place_symlinks = _placement_additions(install.get("place", []))
    service_symlinks, service_starts, stops = _service_additions(install.get("service", []))
    data_dirs = [DATA_DIR_TEMPLATE.format(name=name) for name in install.get("data", [])]
    patches = [_instrument_op(entry) for entry in install.get("instrument", [])]
    restart_commands = _restart_commands(install.get("restart", []))
    return {
        "dirs": [*install.get("dirs", []), *data_dirs],
        "templates": [*install.get("templates", []), *place_templates],
        "symlinks": [*install.get("symlinks", []), *place_symlinks, *service_symlinks],
        "patches": [*install.get("patches", []), *patches],
        "start": [*install.get("start", []), *service_starts, *restart_commands],
        "stops": stops,
    }
